In [5]:
import pandas as pd

pandas !

In [4]:

pd.__version__

'2.2.2'

In [5]:
pd.read_csv

<function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default

In [6]:
#Series([배열]) 하면리스트.배열을 인덱싱 붙여서 만들어줌 
data=pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
data[1]

0.5

In [10]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [25]:
data=pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [12]:
data['b']

0.5

In [13]:
data=pd.Series([0.25, 0.5, 0.75, 1.0],
     index=[2,5,3,7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [14]:
#그냥 values만 주는게 아니라, dictionary 구성해서 그거 주고 series해라 하면 훨씬 보기 편함 
population_dict = {'California':38332521,
                   'Texas':26448193,
                   'New York':19651127,
                   'Florida':19552860,
                   'Illinois':12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [37]:
area_dict = { 'California':423967, 'Texas':695662, 'New York':141297, 'Florida':170312, 'Illinois':149995}
area=pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [41]:
df = pd.DataFrame({'pop':population, 
                    'area':area})
df.head(), df.columns, len(df)

(                 pop    area
 California  38332521  423967
 Texas       26448193  695662
 New York    19651127  141297
 Florida     19552860  170312
 Illinois    12882135  149995,
 Index(['pop', 'area'], dtype='object'),
 5)

In [42]:
type(df['area'])

pandas.core.series.Series

In [43]:
#cal 어쩌구는 key니까, 그냥 area만 가져와라고 해도 key도 함께 산출하는거지 
df['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [17]:
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [21]:
a=pd.Series([2,4,6])
a

0    2
1    4
2    6
dtype: int64

In [23]:
type(a.values)

numpy.ndarray

In [29]:
#data, index 순서라고 할때 그냥 data를 똑같은 값 반복되는 값으로 줄수도 있음 
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [27]:
#but {dictionary}일때는 key를 index로 취한다는거. 그럼 pandas 안에서의 index를 key로 생각해줘야하는거겠지!
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3,2])

3    c
2    a
dtype: object

In [31]:
#dataframe-columns를 부여함으로써 열 데이터로 이루어진 series에 이름을 매핑한다. 
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [33]:
data = [{'a':i, 'b':2*i}
        for i in range(3)] #i는 0,1,2반복하며 열의 column을 부여함 
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [34]:
#dictionary로서 dataFrame 하면 key가 column값이 되는건데, 그 키가 누락되더라도 그 자리를 Nan(not a number)으로 채운다.
pd.DataFrame([{'a':1, 'b':2},{'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [38]:
#population이랑 area는 둘다 series 객체인데, 이걸 딕셔너리로 구성해서 프레임할수도있음. 
pd.DataFrame({'population':population, 'area':area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [4]:
import numpy as np

In [40]:
pd.DataFrame(np.random.rand(3,2), #2차원배열을 랜덤데이터값으로 준다고 정하고 column, index각각줌 
             columns=['foo','bar'],
             index=['a','b','c'])

foo       bar
a  0.646192  0.024221
b  0.712163  0.028832
c  0.379704  0.720172

In [44]:
df=pd.read_csv('./president_heights.csv')

In [55]:
#head는 보통 앞쪽의 다섯개 이렇게만해도 csv를 frame으로뱉다니 대박 
#앞쪽 01234는 dataframe이 자동으로 붙인 index임 order는 csv안에 내용으로 들어있는거 
df.head(10)

order                    name  height(cm)
0      1       George Washington         189
1      2              John Adams         170
2      3        Thomas Jefferson         189
3      4           James Madison         163
4      5            James Monroe         183
5      6       John Quincy Adams         171
6      7          Andrew Jackson         185
7      8        Martin Van Buren         168
8      9  William Henry Harrison         173
9     10              John Tyler         183

In [52]:
np.average(df['height(cm)'])

179.73809523809524

In [53]:
#column에 대한 정보를 주세요
#non-null count 값이 다 차있냐고. null값이 있으면 데이터 분석때 오류가 나오니까 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   order       42 non-null     int64 
 1   name        42 non-null     object
 2   height(cm)  42 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 1.1+ KB


In [54]:
#index를 보면 특이점.. 자기가 알아서 describe해주는 통계 정보들 - so first of all, i should send < head.info.describe >
df.describe()

order  height(cm)
count  42.000000   42.000000
mean   22.476190  179.738095
std    13.152461    7.015869
min     1.000000  163.000000
25%    11.250000  174.250000
50%    22.000000  182.000000
75%    33.750000  183.000000
max    44.000000  193.000000

In [76]:
#index객체-shape도 있고 배열형태처럼. 
ind = pd.Index([2,3,5,7,11])
ind, ind.shape, ind.ndim, ind.dtype

(Index([2, 3, 5, 7, 11], dtype='int64'), (5,), 1, dtype('int64'))

In [57]:
ind[1], ind[::2]

(3, Index([2, 5, 11], dtype='int64'))

In [58]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [59]:
#index객체는 변경이 불가능하세요.환불변경불가세요.슬라이싱이나 값 가져오기는되시는데 변경불가시거든요.
ind[1] =0

TypeError: Index does not support mutable operations

In [7]:
indA=pd.Index([1,3,5,7,9])
indB=pd.Index([2,3,5,7,11])
indA.intersection(indB), indA.union(indB), indA.difference(indB)

(Index([3, 5, 7], dtype='int64'),
 Index([1, 2, 3, 5, 7, 9, 11], dtype='int64'),
 Index([1, 9], dtype='int64'))

In [64]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [65]:
'a' in data

True

In [66]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [67]:
#딕셔너리한테 하듯이, data의 items를 가져와달라고 하면 딕셔너리처럼 묶어서 list화 하고 키밸류 키밸류로 반납해줌 
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [69]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [70]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [71]:
#엥 a.b로 인덱스가 이루어져있음에도 불구하고.. 0:2를 줘도 정상작동이 되노
data[0:2]

a    0.25
b    0.50
dtype: float64

In [72]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [73]:
data [['a','e']]

a    0.25
e    1.25
dtype: float64

In [78]:
data=pd.Series(['a','b','c'], index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [81]:
#loc속성은 명시적 인덱스를 참조하여 인덱싱.슬라이싱둘다가능
#명시적 인덱스니까 말그대로 암묵적이 아니고, 눈에보이는거 자체를 key로 참조한다. 그러니까 loc는 1번째 인덱스가 아니고 진짜 key값이 1인 인덱스를 가져온다. 
data.loc[1]

'a'

In [82]:
#명시적인덱스.  loc니까 인덱스가 아니고 진짜 숫자 1부터 3까지 가져온다. 
data.loc[1:3]

1    a
3    b
dtype: object

In [83]:
#iloc를 하면 암묵적스타일로 다시. 그러니까 인덱스자리 1인 아이의 value값 산출 
data.iloc[1]

'b'

In [84]:
#다시 인덱스 1,2번째애들 산출. 
data.iloc[1:3]

3    b
5    c
dtype: object

In [87]:
data = pd.DataFrame({'area':area, 'pop':population })
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [88]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [90]:
# 와우 이방법으로 새로운열 추가가 된다... ㅁㅊ 
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [92]:
#keys만 배열로 뱉어주세요. 하면 index([]) 이렇게 index로뱉어주네 
#values는 array로뱉네 히얀하다 히얀해 
data.keys(), data.values

(Index(['area', 'pop', 'density'], dtype='object'),
 array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
        [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
        [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
        [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
        [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]]))

In [95]:
#아니 이렇게 했을뿐인데 그냥 true false로 인덱스 달아서 뱉어주네 
xxx_mask = area > 200000
xxx_mask 

California     True
Texas          True
New York      False
Florida       False
Illinois      False
dtype: bool

In [96]:
#위에서 조건문을 변수 이름으로 만들어놓고 그거만 가져와라고하면 가져오네... 
area [ xxx_mask]

California    423967
Texas         695662
dtype: int64

In [98]:
#데이터프레임 df의 40번 행에서 'name' 열부터 'height' 열까지의 데이터를 선택합니다
#dataFrame에서 행과 열을 라벨 기반으로 선택하기 위해서는 loc
df.loc[40, 'name':'height']

name          George W. Bush
height(cm)               182
Name: 40, dtype: object

In [99]:
#numpy랑 비슷하게 쓰려면 iloc
#왜냐하면 loc는 라벨기반이고 iloc는 위치기반이라서 오류가 좀더 적음
#loc는 column으로 선택하는데, iloc는 숫자기반으로 숫자만선택하기때문에. 
# 0행인덱스에 1:3 슬라이싱해서 가져온다 
df.iloc[0, 1:3]

name          George Washington
height(cm)                  189
Name: 0, dtype: object

In [100]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [101]:
#row. column을 뒤바까주노 (5,3)을 (3,5)로
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [102]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [103]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [106]:
#:3은 첫3개요소이므로 3 미포함. :2도 2개이므로.
#iloc를 통해서 열 레이블 자체를 그대로 유지하면서 인덱싱해올수도있음.
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [107]:
#이건확실히 조금더 명시적이쥐 그러니까 진짜 florida까지. 그리고 pop까지인거야
#data.loc[행범위, 열범위]
data.loc[:'Florida', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860

In [110]:
# 데이터값 조건, [col, col]
data.loc[data.density>110, ['pop']]

pop
New York  19651127
Florida   19552860

In [111]:
data.loc[data.density>130, ['pop', 'density']]

pop     density
New York  19651127  139.076746

In [114]:
data.iloc[0,2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [119]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [124]:
#출력형태: numpy 
data.values[0:3, 1:3]

array([[3.83325210e+07, 9.00000000e+01],
       [2.64481930e+07, 3.80187404e+01],
       [1.96511270e+07, 1.39076746e+02]])

In [126]:
#그냥 .column만 잡아도 이런값이...
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [131]:
#출력형태 : dateframe 위에 numpy한거랑 값은 결국 같지! 데이터타입은다름 
#    iloc - dataFrame 연결!!!!!
a=data.iloc[0:3, 1:3]
a

pop     density
California  38332521   90.000000
Texas       26448193   38.018740
New York    19651127  139.076746

In [134]:
#loc도 dataFrame으로 뱉어내지만 숫자가 아니고 column값을 직접 이야기한다는점. 
data.loc[data.area>150000]

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
Florida     170312  19552860  114.806121

In [137]:
data[:1]
# data[1] 하면 값 안나옵니데이 

area       pop  density
California  423967  38332521     90.0

In [139]:
rng = np.random.RandomState(42)
#0부터 10까지, 4개의 int를 series화->인덱스붙여서 출력.
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [141]:
#0부터10까지난수생성 3행4열로뱉고 칼럼값을준거 frame으로 뱉기
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A','B','C','D'])
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [142]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [143]:
np.sin(df*np.pi/4)

A         B         C         D
0  7.071068e-01 -0.707107 -0.707107  0.707107
1  1.224647e-16  0.000000  0.707107 -0.707107
2 -2.449294e-16  0.000000  0.707107  1.000000

In [150]:
area = pd.Series({'Alaska':1723337, 'Texas':695662, 'California':423967}, name='area')
population = pd.Series({'California':38332521, 'Texas':26448193, 'New York':19651127}, name='population')
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [145]:
# 와우 인구밀도 계산하기위해 
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [148]:
area.index.intersection(population.index)

Index(['Texas', 'California'], dtype='object')

In [151]:
#A에 3이 없음에도 인덱스를 유지해서 NaN으로라도 출력하는 히얀한..
#모든기준은 인덱스가 되기 때문에 걔를 기준으로 해서 출력을한다. It's like Primary KEY!!!
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])
A + B 

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [152]:
A.add(B, fill_value=0)
#A.add(B)는 A+B와 같지만, 누락된 요소를 채우기로. null값있는건 value를 0으로 채워서 NULL없앨수있도록 함

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [153]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
#헤엑 'AB'가 아니고 list('AB')라서 이걸 알아서 슬라이싱해서 column을 잡노
A

A   B
0  11  19
1   2   4

In [158]:
B=pd.DataFrame(rng.randint(0, 10, (3,3)),
               columns=list('BAC'))
B

B  A  C
0  9  8  9
1  4  1  3
2  6  7  2

In [159]:
A+B

A     B   C
0  19.0  28.0 NaN
1   3.0   8.0 NaN
2   NaN   NaN NaN

In [160]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0  19.0  28.0  18.0
1   3.0   8.0  12.0
2  16.0  15.0  11.0

In [161]:
#None이 object이니까 다른애들도 object됨 들어가있는순간.. 그래서 sum도 불가해짐 ㅠ 
vals1 = np.array([1, None, 2, 3])
vals1

array([1, None, 2, 3], dtype=object)

In [182]:
#헐 근데... np.nan으로 넣으니까 object가 아니고 float로 타입이 되네
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [162]:
%timeit np.arange(1E6, dtype=int).sum()

1.25 ms ± 21 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [163]:
%timeit np.arange(1E6, dtype=object).sum()

37.7 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [165]:
#아놔 np.nan 이쉑땜에 모든게 다 nan으로 감염되어버릿네
1 + np.nan

nan

In [166]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [167]:
#so nansum하면 배열안에 nan이 있어도 피할수있따구 
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [168]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [169]:
x=pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [170]:
x[0]=None

In [171]:
pd.Series([1, np.nan, 2, None, pd.NA], dtype='Int32')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

In [172]:
data = pd.Series([1, np.nan, 'hello', None])
#null인지아닌지 boolean으로 반환하기
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [173]:
#data중에서 notnull만 가져오기
data[data.notnull()]

0        1
2    hello
dtype: object

In [174]:
#NA값 제거하기
data.dropna()

0        1
2    hello
dtype: object

In [177]:
#이 배열들을 fram할게요 인덱스는알아서붙여주세요
df = pd.DataFrame([[1, np.nan, 2],
                   [2,   3,    5],
                   [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [178]:
#null값이 있는 모든행 삭제..아니그냥 nall하나로있으면 아니그냥다삭제 이건 행기준
df.dropna()

0    1  2
1  2.0  3.0  5

In [179]:
#똑같이 dropna인데 columns를 축으로 해서, 모든열 삭제. 열중에 nan있는거 삭제 
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [180]:
df[3]=np.nan
df


0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [181]:
#어디볼건데?축 열로. 어떻게?all. 데이터값이 all nan인것만 drop하고 반환
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [183]:
#rows볼건데, thresh=3. 최소 nan아닌게 3개가 있는 애들만 살린다. 
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [184]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [185]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [186]:
#앞선값으로 null값채우기
data.fillna(method='ffill')

C:\Users\user\AppData\Local\Temp\ipykernel_13412\1844443866.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [187]:
#뒷값으로 null값채우기
data.fillna(method='bfill')

C:\Users\user\AppData\Local\Temp\ipykernel_13412\742528731.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')


a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [188]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [189]:
#axis=1하면 행기준으로간다 그래서 행에서 그앞에걸로 채우게 되어잇음 
df.fillna(method='ffill', axis=1)

C:\Users\user\AppData\Local\Temp\ipykernel_13412\901808322.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1)


0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [190]:
titanic_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [191]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [194]:
avg_age=np.nanmean(titanic_df.Age.values)
avg_age

29.69911764705882

In [196]:
#fillna(non을 뭘로 채울지 적는거지)
new_df = titanic_df['Age'].fillna(avg_age)
new_df

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...    
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64